<a href="https://colab.research.google.com/github/nivin18/RealTimeMLProjects/blob/master/Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import numpy as np
import pandas as pd

Importing Dataset

In [6]:
dataset = pd.read_csv("car_data.csv")
dataset.head(10)

name  year  selling_price  km_driven    fuel  \
0              Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2       Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3     Datsun RediGO T Option  2017         250000      46000  Petrol   
4      Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   
5       Maruti Alto LX BSIII  2007         140000     125000  Petrol   
6  Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol   
7   Tata Indigo Grand Petrol  2014         240000      60000  Petrol   
8   Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol   
9   Maruti Celerio Green VXI  2017         365000      78000     CNG   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  
5  Individual       Manual   First Owner  
6  Individual       Manual   First Owner  
7  Individual       Manual  Second Owner  
8  Individual       Manual   First Owner  
9  Individual       Manual   First Owner

In [8]:
dataset['owner'].isnull().sum()

0

In [9]:
dataset['owner'].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [10]:
dataset['seller_type'].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [11]:
dataset['fuel'].value_counts()

Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: fuel, dtype: int64

Encoding the Data

In [43]:
x = dataset.iloc[:, [1,3,4,6]].values
y = dataset.iloc[:,2].values

In [44]:
x

array([[2007, 70000, 'Petrol', 'Manual'],
       [2007, 50000, 'Petrol', 'Manual'],
       [2012, 100000, 'Diesel', 'Manual'],
       ...,
       [2009, 83000, 'Petrol', 'Manual'],
       [2016, 90000, 'Diesel', 'Manual'],
       [2016, 40000, 'Petrol', 'Manual']], dtype=object)

In [45]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:, 2] = lb.fit_transform(x[:,2])
lb1 = LabelEncoder()
x[:,3] = lb1.fit_transform(x[:, 3])

In [46]:
x[:,2]

array([4, 4, 1, ..., 4, 1, 4], dtype=object)

In [47]:
x

array([[2007, 70000, 4, 1],
       [2007, 50000, 4, 1],
       [2012, 100000, 1, 1],
       ...,
       [2009, 83000, 4, 1],
       [2016, 90000, 1, 1],
       [2016, 40000, 4, 1]], dtype=object)

Splitting the data into Train and Test set

In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)
print(x_test[:,:])

[[2012 70070 1 0]
 [2013 86000 1 0]
 [2014 120000 4 1]
 ...
 [2013 42000 4 1]
 [2005 60000 4 1]
 [2018 10000 1 0]]


Training the Model


In [49]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=300, random_state=0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [50]:
accuracy = regressor.score(x_test, y_test)
print(accuracy*100,'%')

75.79783473129758 %


Performing a Test on Given input

In [60]:
new_data = [2015,10000,"Petrol","Manual"]
new_data[2] = lb.transform([new_data[2]])[0]
new_data[3] = lb1.transform([new_data[3]])[0]

The Bottom part is the price the model predicted

In [61]:
print(new_data)
regressor.predict([new_data])

[2015, 10000, 4, 1]


array([650448.14814815])

Saving the Model and Encoder using Pickle

In [65]:
import pickle
pickle.dump(regressor,open('regressor.pk1','wb' ))
pickle.dump(lb,open('lb','wb'))
pickle.dump(lb1,open('lb1','wb'))